server:
  port: 8080
  servlet:
    context-path: /api/v1/gateway

spring:
  application:
    name: ROOMBILLZ-GATEWAY-SERVICE
    
  profiles:
    active: local
    
# ==============================
# ACTUATOR CONFIG
# ==============================
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, beans, env, metrics, prometheus

  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
    